#!/bin/sh 
#
# liferay:   Liferay Svetpet porta 80
#
# chkconfig: 345 26 74
# description: Liferay Portal Tomcat 
#
#

# Sanity checks.
LIFERAY_TOMCAT_HOME=/opt/liferay-portal-6.2-ce-ga4/tomcat-7.0.42
[ -x ${LIFERAY_TOMCAT_HOME}/bin/startup.sh ] || exit 0

RETVAL=0

start() {
    echo -n $"Starting Liferay Portal: "
    rm -rf ${LIFERAY_TOMCAT_HOME}/temp/*
    ${LIFERAY_TOMCAT_HOME}/bin/startup.sh
    RETVAL=$?
    echo
}
cleanup() {
    echo -n $"Cleaning Tomcat: "
    rm -rf ${LIFERAY_TOMCAT_HOME}/temp/*
    rm -rf ${LIFERAY_TOMCAT_HOME}/work/Catalina/localhost
    echo OK
}
stop() {
    echo -n $"Stopping Liferay Portal: " 
    ${LIFERAY_TOMCAT_HOME}/bin/shutdown.sh
    RETVAL=$?
    echo
}

forcestop() {
    echo -n $"Force Stopping Liferay Portal: " 
    /usr/bin/pkill -f ${LIFERAY_TOMCAT_HOME}
    RETVAL=$?
    echo
}
status() {
    echo -n $"Liferay Portal: " 
    /usr/bin/pgrep -l -f ${LIFERAY_TOMCAT_HOME}
    RETVAL=$?
    echo
}
# See how we were called.
case "$1" in
    cleanup)
        stop
	echo "Waiting 10 sec..."
	sleep 10
	cleanup
	;;
    start_cleanup)
        stop
	echo "Waiting 10 sec..."
	sleep 10
	cleanup
	start
	;;
    start)
        start
        ;;
    stop)
        stop
        ;;
    forcestop)
        forcestop
        ;;
    status)
        status 
        ;;
    restart)
        stop
	sleep 3
	forcestop
	sleep 1
        start
        ;;
    *)
        echo $"Usage: $0 {start|start_cleanup|cleanup|stop|forcestop|restart|status}"
        ;;
esac
exit $RETVAL
